# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 266ccba208b66d0232a288ba8a852958a56a3c09c406a1af9397f82e27bdb7dc92df3715f2b646180db07b6bce43df209a6b9b23fcc1817822336b047a31fea4

test:
  secret_key_base: ea20e64593d6ccfed9fa735b29a3bf1e353770a7079d3e1fa52268acd5d4e0ce4a963cc3a6fa0505c5b2b3c5d8580c0470801dff39fe756a5c3fb14110f31298

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
